BEIUFIN_LED_RGB_HUI(19) // R
BEIUFIN_LED_RGB_HUD(34) // F
BEIUFIN_LED_RGB_SAI(20) // T
BEIUFIN_LED_RGB_SAD(35) // G
BEIUFIN_LED_RGB_VAI(17) // W
BEIUFIN_LED_RGB_VAD(32) // S
BEIUFIN_LED_RGB_SPI(33) // D
BEIUFIN_LED_RGB_SPD(31) // A
